services:

  odoo:
    image: odoo:latest
    container_name: odoo
    restart: unless-stopped 
    depends_on:
      - db
    ports:
      - "8081:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo  #Cambiar si no es entorno de pruebas
      - PASSWORD=odoo
    command: odoo -d odoo --db_user=odoo --db_password=odoo -i base      

  db:
    image: postgres:16.0
    container_name: db
    restart: unless-stopped       
    environment:
      - POSTGRES_DB=odoo #Cambiar con las mismas credenciales de arriba si no es entorno de pruebas
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  db-data:    

      
